[package]
name = "FILLME"
edition = "2021"
authors = ["FILLME"]
license = "FILLME"

[dependencies]
futures-util = { version = "0.3", default-features = false }
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
twilight-cache-inmemory = { version = "0.15", features = ["permission-calculator"] }
twilight-gateway = { version = "0.15", features = ["rustls-webpki-roots", "simd-json", "zlib-simd"] }
twilight-http = { version = "0.15", features = ["rustls-webpki-roots", "simd-json", "trust-dns"] }
twilight-mention = "0.15"
twilight-model = "0.15"
twilight-standby = "0.15"
twilight-util = { version = "0.15", features = ["builder", "link", "permission-calculator", "snowflake"] }
twilight-validate = "0.15"
